name: CMake

on:
  push:
    branches: [ develop ]

env:
  # Определяем тип построения CMake (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # Строим на MacOS
    runs-on: macos-latest

    steps:
    #- name: Делаем pull проекта из репозитория/Удаляем клонированный репозиторий
      uses: actions/checkout@v2

    - name: Конфигурируем построение CMake
      run: cmake -S ${{github.workspace}}/algo_laba5_3 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Запускаем построение CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Закачиваем построенный исполняемый файл
      uses: actions/upload-artifact@v1
      with:
        # Определяем имя архива и его содержимое 
        name: algo_laba5_3_executable
        path: ${{github.workspace}}/build/algo_laba5_3
